# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=your-256-bit-secret-key-change-this-in-production-make-it-long
jwt.expiration=86400000

# Server
server.port=8081

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudflare AI
cloudflare.account.id=a3f84780fd1f6d1e93c931ab498d312a
cloudflare.api.token=cfut_Cxh1VJmbpeneARJrVi2RTem1rOd1Ss0jxH7vd3dib65fe084

# Brevo Email
brevo.api.key=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
brevo.sender.email=yuriix2003@gmail.com
brevo.sender.name=Job Tracker Alerts

# Firebase Storage (we'll configure this later)
firebase.storage.bucket=job-tracker-b1138.firebasestorage.app
firebase.credentials.path=src/main/resources/job-tracker-b1138-firebase-adminsdk-fbsvc-65dca07c07.json